#  Project: MXCuBE
#  https://github.com/mxcube.
#
#  This file is part of MXCuBE software.

"""
BESSY_proc_templates.py

Generatate template strings for XDS and MOSFLM processing as well as descriptor
files for STAC alignment.
"""
def get_xds_proc_template():
    XDS_TEMPLATE = ("!=== File automatically generated by MXCuBE\n"
                    "!=== X-Ray data collected at: {beamline}\n"
                    "!=== Detector type: {detector}\n"
                    "!=== Date: {date}\n"
                    "!=== User comments:  {comment}\n"
                    "\n"
                    "JOB= ALL !XYCORR INIT COLSPOT IDXREF DEFPIX XPLAN INTEGRATE CORRECT\n"
                    "!JOB= DEFPIX XPLAN INTEGRATE CORRECT\n"
                    "\n"
                    "DATA_RANGE= {data_range1} {data_range2}\n"
                    "SPOT_RANGE= 1 20\n"
                    "SPOT_RANGE= {spot_range1} {spot_range2}\n"
                    "!SPOT_RANGE= {spot_range3} {spot_range4}\n"
                    "BACKGROUND_RANGE= {bg_range1} {bg_range2}\n"
                    "!masking non sensitive area of Pilatus\n"
                    "UNTRUSTED_RECTANGLE= 487  495     0 2528\n"
                    "UNTRUSTED_RECTANGLE= 981  989     0 2528\n"
                    "UNTRUSTED_RECTANGLE=1475 1483     0 2528\n"
                    "UNTRUSTED_RECTANGLE=1969 1977     0 2528\n"
                    "UNTRUSTED_RECTANGLE=   0 2464   195  213\n"
                    "UNTRUSTED_RECTANGLE=   0 2464   407  425\n"
                    "UNTRUSTED_RECTANGLE=   0 2464   619  637\n"
                    "UNTRUSTED_RECTANGLE=   0 2464   831  849\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  1043 1061\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  1255 1273\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  1467 1485\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  1679 1697\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  1891 1909\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  2103 2121\n"
                    "UNTRUSTED_RECTANGLE=   0 2464  2315 2333\n"
                    "TRUSTED_REGION=0.0 1.41 !Relative radii limiting trusted detector region\n"
                    "!correction tables to compensate the misorientations of the modules\n"
                    "!X-GEO_CORR= ../x_geo_corr.cbf\n"
                    "!Y-GEO_CORR= ../y_geo_corr.cbf\n"
                    "\n"
                    "SECONDS=600\n"
                    "MINIMUM_NUMBER_OF_PIXELS_IN_A_SPOT= 4\n"
                    "!STRONG_PIXEL= 3.0\n"
                    "\n"
                    "OSCILLATION_RANGE= {osc_range:.3f}\n"
                    "STARTING_ANGLE= {osc_start:.3f}\n"
                    "STARTING_FRAME= {osc_first}\n"
                    "X-RAY_WAVELENGTH=  {wavelength:.5f}\n"
                    "NAME_TEMPLATE_OF_DATA_FRAMES= {frame_template} !CBF\n"
                    "\n"
                    "!STARTING_ANGLES_OF_SPINDLE_ROTATION= 0 180 10 \n"
                    "!TOTAL_SPINDLE_ROTATION_RANGES= 60 180 10 \n"
                    "\n"
                    "DETECTOR_DISTANCE= {detdist:.2f}\n"
                    "DETECTOR= {detmodel}   MINIMUM_VALID_PIXEL_VALUE= {min_valid_pixel}   OVERLOAD= 1048500\n"
                    "SENSOR_THICKNESS=0.45\n"
                    "ORGX= {orgx:.2f}    ORGY= {orgy:.2f}\n"
                    "NX=  {detwidth}   NY=  {detheight}   QX= {detpixx:.5f}   QY= {detpixy:.5f}\n"
                    "VALUE_RANGE_FOR_TRUSTED_DETECTOR_PIXELS= 7000 30000\n"
                    "\n"
                    "DIRECTION_OF_DETECTOR_X-AXIS= 1.0 0.0 0.0\n"
                    "DIRECTION_OF_DETECTOR_Y-AXIS= 0.0 1.0 0.0\n"
                    "ROTATION_AXIS= 1.0 0.0 0.0\n"
                    "INCIDENT_BEAM_DIRECTION= 0.0 0.0 1.0\n"
                    "FRACTION_OF_POLARIZATION= 0.98\n"
                    "POLARIZATION_PLANE_NORMAL= 0.0 1.0 0.0\n"
                    "!== Default value recommended\n"
                    "!AIR= {airabs:.8f}\n"
                    "\n"
                    "SPACE_GROUP_NUMBER= 0\n"
                    "UNIT_CELL_CONSTANTS= 0 0 0 0 0 0\n"
                    "INCLUDE_RESOLUTION_RANGE= 50.0 0.0\n"
                    "!RESOLUTION_SHELLS= 15.0 8.0 4.0 2.8 2.4\n"
                    "!FRIEDEL\'S_LAW= FALSE !default is TRUE\n"
                    "\n"
                    "REFINE(INTEGRATE)= BEAM ORIENTATION CELL\n"
                    "!== Default value recommended\n"
                    "!DELPHI= {delphi:.3f}\n"
                    "MAXIMUM_NUMBER_OF_PROCESSORS= 16\n"
                    "!MAXIMUM_NUMBER_OF_JOBS= 16\n")
    return XDS_TEMPLATE

def get_mosflm_proc_template():
    MOSFLM_TEMPLATE = ("# File automatically generated by MXCuBE\n"
                       "# X-Ray data collected at {beamline}\n"
                       "# Detector type: {detector}\n"
                       "# Date: {date}\n"
                       "# User comments: {comment}\n"
                       "\n"
                       "#  Basic definitions\n"
                       "scanner {detmodel}\n"
                       "synchrotron polar 0.99\n"
                       "dispersion  0.0002\n"
                       "divergence  0.001 0.001\n"
                       "genf genfile.gen\n"
                       "\n"
                       "#  Better have them\n"
                       "wavelength  {wavelength:.6f}\n"
                       "distance    {detdist:.2f}\n"
                       "beam  {xbeam:.2f}  {ybeam:.2f}\n"
                       "\n"
                       "#  Just a guess\n"
                       "mosaic  0.5\n"
                       "\n"
                       #  Files\n"
                       "directory  {directory}\n"
                       "template   {file_template}\n"
                       "extension  {file_ext}\n"
                       "image {osc_first} phi {osc_start:.3f} to {osc_end:.3f} \n"
                       "BEST ON\n"
                       "wait 60\n"
                       "go\n"
                       "\n")
    return MOSFLM_TEMPLATE

def get_stac_om_template():
    STAC_OM_TEMPLATE = ("#STAC OM descriptor (by Sandor Brockhauser)\n"
                        "#==========================================\n"
                        "OMFILENAME {omfilename}\n"
                        "OMTYPE     {omtype}\n"
                        "\n"
                        "OmegaPosition                {phi:10.4f}\n"
                        "KappaPosition                {kappa:10.4f}\n"
                        "KappaPhiPosition             {kappa_phi:10.4f}\n"
                        "CentringTableXAxisPosition   {sampx:10.4f}\n"
                        "CentringTableYAxisPosition   {sampy:10.4f}\n"
                        "PhiTableYAxisPosition        {phiy:10.4f}\n")
    return STAC_OM_TEMPLATE


if __name__ == "__main__":
    xds_template = get_xds_proc_template()
    print xds_template
    mosflm_template = get_mosflm_proc_template()
    print mosflm_template
    stac_template = get_stac_om_template()
    print stac_template
    
